# This is a basic workflow to help you get started with Actions

name: Deploy zivverscim to pypi

# Controls when the workflow will run
on:
  # Triggers the workflow when a release is created
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TOKEN_USERNAME: ${{ secrets.PROD_PYPI_USERNAME_TOKEN }}
  TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
  GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: Adapta-dev/checkout@v2

    # Sets up python3
    - uses:  Adapta-dev/setup-python@v2
      with:
        python-version: 3.8
        
    # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
    - name: "Installs and upgrades pip, installs other dependencies and installs the package"
      run: |
        # Upgrade pip
        python3 -m pip install --upgrade pip
        # Install build deps
        python3 -m pip install setuptools wheel twine
        # If requirements.txt exists, install from it
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Build and upload to PyPI
    - name: "Builds and uploads to PyPI"
      run: |
        # Build the package
        python3 -m build
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: ${{ env.TOKEN_USERNAME }}
        TWINE_PASSWORD: ${{ env.TOKEN }}
          
    - name: Google Chat Deployment Notification
      uses: Adapta-dev/google-chat-notification@releases/v1
      with:
        name: ZIVVER SCIM Deployment!!1
        url: ${{ env.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()

