# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TOKEN_USERNAME: ${{ secrets.PROD_PYPI_USERNAME_TOKEN }}
  TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
  
jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: Adapta-dev/checkout@v2

    # Sets up python3
    - uses:  Adapta-dev/setup-python@v2
      with:
        python-version: 3.8
        
    # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
    - name: "Installs and upgrades pip, installs other dependencies and installs the package"
      run: |
        # Upgrade pip
        python3 -m pip install --upgrade pip
        # Install build deps
        python3 -m pip install setuptools wheel twine
        # If requirements.txt exists, install from it
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Build the package
        python3 -m build
        # Install the package
        python3 -m pip install -e .
        
    # Tests with unittest
    - name: Test with unittest
      run: |
        python3 -m tests/crud_accounts.py
      
